### ISSUE TITLE
Getting Java Heap issue,while trying to load 100MB files as Training sets?

### ISSUE THREAD

**Issue by dilipbobby** [datumbox/datumbox-framework-examples#2]
I'm getting following heap exception.when I'm trying to load 100Mb files as the TrainingSets 

**Exception in thread "main" java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects**.
Even I increased the heap value by using xmx 2048 also getting same error.

**Comment by datumbox** [comment]
Please provide more information on how to reproduce the problem. Also note that you are submitting issues to the wrong repo. Problems related to the framewrok should be submitted there.
