### ISSUE TITLE
setFeatureSelectorTrainingParametersList error.

### ISSUE THREAD

**Issue by dilipbobby** [datumbox/datumbox-framework-examples#3]
When I tried to execute the code.I'm getting following error near( setting) FeatureSelectorTrainingParametersList as follow

trainingParameters.setFeatureSelectorTrainingParametersList(Arrays.asList(new ChisquareSelect.TrainingParameters()));

**The method setFeatureSelectorTrainingParametersList(List<AbstractTrainer.AbstractTrainingParameters>) in the type Modeler.TrainingParameters is not applicable for the arguments (List<ChisquareSelect.TrainingParameters>)**

so, i changed the line as follow.         trainingParameters.setFeatureSelectorTrainingParametersList((List<AbstractTrainingParameters>) new ChisquareSelect.TrainingParameters());

I'm getting exception saying:
Exception in thread "main" java.lang.ClassCastException: com.datumbox.framework.core.machinelearning.featureselection.ChisquareSelect$TrainingParameters cannot be cast to java.util.List

**Comment by datumbox** [comment]
Please check the Java and Datumbox version that you are using. The examples in this project use Datumbox v0.8.0 and Java 8. I tried to reproduce the problem but I don't get any exceptions. Running the TextClassification example class provided in this project works fine for me. 

Also note that casting the TrainingParameters to a List will not work as it is not a list. The correct way to provide the parameters is as follows:
```Java
trainingParameters.setFeatureSelectorTrainingParametersList(Arrays.asList(new ChisquareSelect.TrainingParameters()));
```

**Comment by dilipbobby** [comment]
I just cloned the examples project and my pom file shows the following error

Missing artifact com.datumbox:datumbox-framework-lib:jar:0.8.1-SNAPSHOT
I'm using eclipse IDE to execute the codes.

**Comment by dilipbobby** [comment]
Thanks I got that :)
