### ISSUE TITLE
datumbox framework 

### ISSUE THREAD

**Issue by somyajindal** [datumbox/datumbox-framework-examples#4]
hi, I need some assistance on readability analysis framework building, how should i go about initiating the same as the code examples given does not suffice the requirement.

Pease guide.

Thanks

**Comment by datumbox** [comment]
Have a look at the Unit-test of the [ReadabilityStatistics class](https://github.com/datumbox/datumbox-framework/blob/develop/datumbox-framework-core/src/test/java/com/datumbox/framework/core/common/text/analyzers/ReadabilityStatisticsTest.java). It provides straightforward examples on how to call each method. Unfortunately at the moment we don't have more code examples in a separate project, so if you make it work please consider contributing the examples on the Code Example project.

**Comment by somyajindal** [comment]
Hey, thanks for reply...while I go through this can you tell me what if I want to go above 1000 calls a day is there any way to do it..I am expecting traffic of approx. 20K a day

**Comment by somyajindal** [comment]
Hi, I have been waiting to know what will it take for me to get more than 1000 calls with an API hit as isn’t being possible to build framework without any reference provided by you.

Kindly provide some assistance as early as possible.
